Repository Walkhub/walkhub_android, pull requests merged in 2022-04, with the labels that each got.

#375 🔀 :: (#363) hub view detail
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchSchoolViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchUserViewModel.kt
  presentation/src/main/res/layout/fragment_hub_rank.xml
Labels: 기능 추가

#380 🔀 :: (#376) sign up class
  data/src/main/java/com/semicolon/data/local/entity/rank/OurSchoolUserRankRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/OurSchoolUserRankResponse.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/OurSchoolUserRankEntity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/MySchoolUserRankData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/SignUpClassActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/SignUpClassViewModel.kt
  presentation/src/main/res/layout/fragment_hub_rank.xml
Labels: 기능 추가

#372 🔀 :: (#365) Connect Mypage ViewModel
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/ProfileFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/ProfileViewModel.kt
Labels: 기능 추가

#374 🔀 :: (#373) check exercise logic
  data/src/main/java/com/semicolon/data/background/worker/SynchronizeExerciseWorker.kt
  data/src/main/java/com/semicolon/data/background/worker/SynchronizeExerciseWorkerFactory.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/api/ExerciseApi.kt
  data/src/main/java/com/semicolon/data/remote/request/exercise/SaveDailyExerciseRequest.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/di/WalkHubApplication.kt
Labels: chore

#384 🔀 :: (#383) 측정 UI 연결
  presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/home/HomeViewModel.kt
Labels: 기능 추가

#386 🔀 :: (#381) hub 정보 ui
  presentation/src/main/java/com/semicolon/walkhub/ui/cheering/CheeringItemViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubInfoNoticeRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/HubInfoNoticeRvData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/SearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubUserViewModel.kt
  presentation/src/main/res/layout/fragment_hub.xml
  presentation/src/main/res/layout/fragment_hub_info.xml
  presentation/src/main/res/layout/fragment_hub_rank.xml
  presentation/src/main/res/layout/item_cheering.xml
  presentation/src/main/res/layout/item_hub_info_notice.xml
Labels: 기능 추가

#391 🔀 :: (#390) socket chore
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSocketDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSocketDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/SocketRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/repository/SocketRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/socket/ConnectSocketUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/socket/DisconnectSocketUseCase.kt
Labels: chore

#395 🔀 :: (#393) update school
  data/src/main/java/com/semicolon/data/local/dao/SchoolDao.kt
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalSchoolDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalSchoolDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/school/SchoolDetailRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/api/SchoolApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSchoolDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSchoolDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/school/SchoolDetailResponse.kt
  data/src/main/java/com/semicolon/data/repository/SchoolRepositoryImpl.kt
  data/src/test/java/com/semicolon/data/repository/SchoolRepositoryUnitTest.kt
  domain/src/main/java/com/semicolon/domain/entity/school/SchoolDetailEntity.kt
  domain/src/main/java/com/semicolon/domain/repository/SchoolRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/school/FetchSchoolDetailUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/school/SetSchoolLogoUseCase.kt
  presentation/src/main/java/com/semicolon/walkhub/di/LocalDataSourceModule.kt
Labels: 기능 추가

#389 🔀 :: (#369) profile, setting UI 수정 및 추가
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/AccountInfoActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/AccountInfoFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/ModifyHealthInfoActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/ModifyHealthInfoFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/ModifyProfileActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/NoticeSettingActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/SettingActivity.kt
  presentation/src/main/res/drawable/ic_conquer.png
  presentation/src/main/res/layout/activity_account_info.xml
  presentation/src/main/res/layout/activity_modify_health_info.xml
  presentation/src/main/res/layout/activity_modify_profile.xml
  presentation/src/main/res/layout/fragment_profile.xml
Labels: 리팩토링, chore

#397 🔀 :: (#387) hub info 기능 구현
  data/src/main/java/com/semicolon/data/local/converter/TypeConverters.kt
  data/src/main/java/com/semicolon/data/local/dao/SchoolDao.kt
  data/src/main/java/com/semicolon/data/local/entity/school/SchoolDetailRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/response/school/SchoolDetailResponse.kt
  domain/src/main/java/com/semicolon/domain/entity/school/SchoolDetailEntity.kt
  presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt
  presentation/src/main/java/com/semicolon/walkhub/extensions/View.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/HubInfoNoticeRvData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubInfoFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubInfoViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
  presentation/src/main/res/layout/fragment_hub_info.xml
Labels: 기능 추가

#400 🔀 :: (#398) SettingViewModel 분리
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/setting/AccountInfoViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/setting/ModifyHealthInfoViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/setting/ModifyProfileViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/setting/NoticeSettingViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/setting/SettingViewModel.kt
Labels: 리팩토링

#385 🔀 :: (#383) 측정 UI 연결
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSocketDataSourceImpl.kt
  presentation/src/main/java/com/semicolon/walkhub/di/RepositoryModule.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/challenge/ChallengeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/cheering/CheeringItemViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/measure/MeasuringActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/challenge/ChallengeViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/home/HomeViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubUserViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/measure/MeasureHomeViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/measure/MeasureViewModel.kt
  presentation/src/main/res/layout/activity_measure_home.xml
  presentation/src/main/res/layout/activity_measuring.xml
Labels: 기능 추가

#408 🔀 :: (#404) 자잘한 뷰들들 수정
  presentation/src/main/res/layout/activity_modify_profile.xml
  presentation/src/main/res/layout/activity_setting.xml
Labels: chore

#405 🔀 :: (#402) 계정정보 ViewModel -> Activity 결합!
  data/src/main/java/com/semicolon/data/remote/api/UserApi.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/AccountInfoActivity.kt
  presentation/src/main/res/layout/activity_modify_health_info.xml
Labels: 기능 추가

#409 🔀::(#407) chellenge detail
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/challenge/ChallengeDetailViewModel.kt
  presentation/src/main/res/drawable/ic_join_background.xml
  presentation/src/main/res/drawable/oval_number.xml
  presentation/src/main/res/layout/activity_challenge_detail.xml
Labels: 기능 추가

#413 🔀 :: (#412) notifications on off 구현
  data/src/main/java/com/semicolon/data/remote/api/NotificationApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteNotificationDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteNotificationDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/NotificationRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/enums/NotificationType.kt
  domain/src/main/java/com/semicolon/domain/param/notifications/SwitchOnNotificationsParam.kt
  domain/src/main/java/com/semicolon/domain/repository/NotificationRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/notification/PatchSwitchOffNotificationUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/notification/PatchSwitchOnNotificationUseCase.kt
Labels: 기능 추가

#416 🔀 :: (#379) Register 구현
  data/src/main/java/com/semicolon/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalNotificationDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/api/UserApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteNotificationDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSchoolDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSchoolDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/request/users/UserSignUpRequest.kt
  data/src/main/java/com/semicolon/data/remote/response/school/SearchSchoolResponse.kt
  data/src/main/java/com/semicolon/data/repository/SchoolRepositoryImpl.kt
  data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
  data/src/test/java/com/semicolon/data/datasource/RemoteSchoolDataSourceUnitTest.kt
  data/src/test/java/com/semicolon/data/datasource/RemoteUserDataSourceUnitTest.kt
  data/src/test/java/com/semicolon/data/repository/SchoolRepositoryUnitTest.kt
  data/src/test/java/com/semicolon/data/repository/UserRepositoryUnitTest.kt
  domain/src/main/java/com/semicolon/domain/entity/school/SearchSchoolEntity.kt
  domain/src/main/java/com/semicolon/domain/enums/SexType.kt
  domain/src/main/java/com/semicolon/domain/param/user/CheckPhoneNumberParam.kt
  domain/src/main/java/com/semicolon/domain/param/user/PostUserSignUpParam.kt
  domain/src/main/java/com/semicolon/domain/param/user/VerifyPhoneNumberSignUpParam.kt
  domain/src/main/java/com/semicolon/domain/repository/SchoolRepository.kt
  domain/src/main/java/com/semicolon/domain/repository/UserRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/badge/FetchUserBadgesUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/notification/ReadNotificationUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/school/SearchSchoolUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/CheckPhoneNumberUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FindUserAccountUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/PatchSchoolUseCase.kt
  domain/src/test/java/com/semicolon/domain/usecase/school/SearchSchoolUseCaseUnitTest.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/ui/HomeActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/ScanHealthInformationActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/SearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/adapter/SearchSchoolAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/model/SecondSearchSchoolData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/ui/Register.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/SearchSchoolViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/login/LoginViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/register/RegisterViewModel.kt
  presentation/src/main/res/layout/activity_register.xml
Labels: 기능 추가

#415 🔀 :: (#388) hub 응원하기
  data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
  presentation/src/main/java/com/semicolon/walkhub/bindingadapter/HubBindingAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/bindingadapter/ImageBindingAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubInfoNoticeRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSchoolRankRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSearchSchoolRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSearchUserRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubUserRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubUserViewModel.kt
  presentation/src/main/res/layout/activity_search_school.xml
  presentation/src/main/res/layout/fragment_hub.xml
  presentation/src/main/res/layout/fragment_hub_info.xml
  presentation/src/main/res/layout/fragment_hub_rank.xml
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/layout/item_hub_user_rank.xml
  presentation/src/main/res/layout/item_search_user.xml
Labels: 기능 추가

#427 🔀 :: (#426) Profile add class grade
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/ProfileFragment.kt
  presentation/src/main/res/layout/fragment_profile.xml
Labels: chore

#432 🔀 :: (#420) rank update
  data/src/main/java/com/semicolon/data/local/converter/TypeConverters.kt
  data/src/main/java/com/semicolon/data/local/dao/RankDao.kt
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalRankDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalRankDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/FetchMySchoolRankRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/SchoolRankAndSearchRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/SchoolRankRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/SearchSchoolRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/SearchUserRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/UserRankRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/api/RankApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/FetchMySchoolRankResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/inquiryRank/school/SchoolRankAndSearchResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/inquiryRank/school/SchoolRankResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/search/school/SearchSchoolResponse.kt
  data/src/main/java/com/semicolon/data/repository/RankRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/FetchMySchoolRankEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/SchoolRankAndSearchEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/SchoolRankEntity.kt
  domain/src/main/java/com/semicolon/domain/param/user/FetchSchoolRankAndSearchParam.kt
  domain/src/main/java/com/semicolon/domain/repository/RankRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/rank/FetchMySchoolRankUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/rank/FetchSchoolRankAndSearchUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/rank/FetchSchoolRankUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/rank/SchoolRankAndSearchUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/rank/SearchSchoolUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSchoolRankRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/HubSchoolRankData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/MySchoolRankData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/UserRankRvData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubInfoFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/SignUpClassActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchSchoolViewModel.kt
  presentation/src/main/res/layout/activity_hub_search_school.xml
Labels: 기능 추가

#423 🔀 :: (#422) 측정 percent 연결
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/bindingadapter/ChallengeBindingAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/bindingadapter/ExerciseBindingAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/measure/MeasuringActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/measure/MeasureViewModel.kt
  presentation/src/main/res/layout/activity_measuring.xml
Labels: 기능 추가

#436 🔀 :: (#435) npe 추가
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/ProfileViewModel.kt
Labels: chore

#434 🔀 :: (#433) 내 학교 정보 조회(앱) 수정
  data/src/main/java/com/semicolon/data/remote/api/RankApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/RankRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/repository/RankRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/rank/FetchMySchoolRankUseCase.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
Labels: 리팩토링

#430 🔀 :: (#429) schoolid 추가
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/model/MyPageData.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/ProfileViewModel.kt
Labels: chore

#438 🔀 :: (#437) 로그인 에러 예외처리
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/login/LoginActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/login/LoginViewModel.kt
Labels: chore

#442 🔀 :: (#440) Register 잔오류들 수정
  data/src/main/java/com/semicolon/data/remote/api/UserApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/request/users/UserSignUpRequest.kt
  data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
  data/src/test/java/com/semicolon/data/datasource/RemoteUserDataSourceUnitTest.kt
  data/src/test/java/com/semicolon/data/repository/UserRepositoryUnitTest.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/HomeActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/login/LoginActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/ScanHealthInformationActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/ui/Register.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/register/RegisterViewModel.kt
Labels: 기능 추가, chore, 버그

#451 🔀 :: (#449) Rank Bug
  data/src/main/java/com/semicolon/data/local/entity/rank/FetchMySchoolRankRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/SearchUserRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/FetchMySchoolRankResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/search/user/SearchUserResponse.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/FetchMySchoolRankEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/SearchUserEntity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSearchUserRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/SearchUserData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/SignUpClassActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchUserViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/SignUpClassViewModel.kt
Labels: chore

#450 🔀 :: (#445) 마이페이지 마지막..
  data/src/main/java/com/semicolon/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/user/UserMyPageRoomEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/users/UserMyPageEntity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/ProfileFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/model/MyPageData.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/ProfileViewModel.kt
  presentation/src/main/res/drawable/profile.png
  presentation/src/main/res/layout/fragment_profile.xml
Labels: 기능 추가, 버그

#447 🔀 :: (#421) 로그아웃 구현
  data/src/main/java/com/semicolon/data/local/datasource/LocalUserDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/storage/AuthDataStorage.kt
  data/src/main/java/com/semicolon/data/local/storage/AuthDataStorageImpl.kt
  data/src/main/java/com/semicolon/data/remote/api/UserApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/repository/UserRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/LogOutUseCase.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/SettingActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/setting/SettingViewModel.kt
Labels: 기능 추가

#452 🔀 :: (#449) 랭크 버그 수정
  data/src/main/java/com/semicolon/data/local/entity/rank/OurSchoolUserRankRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/SchoolRankAndSearchRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/UserRankRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/response/exercise/ExercisingUserListResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/OurSchoolUserRankResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/inquiryRank/user/UserRankResponse.kt
  data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/exercise/ExercisingUserEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/OurSchoolUserRankEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/SchoolRankAndSearchEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/UserRankEntity.kt
  presentation/src/main/java/com/semicolon/walkhub/adapter/RecyclerViewItem.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/cheering/CheeringItemViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSchoolRankRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSearchSchoolRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/HubSchoolRankData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/MySchoolUserRankData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/SchoolUserRankData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/SearchSchoolData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubUserViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/SignUpClassViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/measure/MeasureHomeViewModel.kt
Labels: 기능 추가, chore, 버그

#455 🔀 :: (#454) 반가입 하기 오류 수정
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/SignUpClassActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/SignUpClassViewModel.kt
Labels: chore, 버그

#464 🔀 :: (#463) Notification XML
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/ui/notification/NotificationActivity.kt
  presentation/src/main/res/layout/activity_notification.xml
  presentation/src/main/res/layout/notification_item.xml
Labels: 기능 추가

#462 🔀 :: (#460) 세팅아이콘 추가
  presentation/src/main/res/drawable/ic_setting.png
  presentation/src/main/res/layout/fragment_profile.xml
Labels: 기능 추가, chore
