Repository Walkhub/walkhub_android, pull requests merged in 2022-02, with the labels that each got.

#49 🔀 :: (#48) exercise synchronization
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  data/build.gradle.kts
  data/src/main/java/com/semicolon/data/background/task/ExerciseBackgroundTask.kt
  data/src/main/java/com/semicolon/data/background/task/ExerciseBackgroundTaskImpl.kt
  data/src/main/java/com/semicolon/data/background/worker/SynchronizeExerciseWorker.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/di/WalkHubApplication.kt
Labels: 기능 추가

#54 🔀 :: (#53) challenge remote datasource HttpHandler 사용
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteChallengeDateSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteChallengeDateSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/ChallengeRepositoryImpl.kt
Labels: chore

#47 🔀 :: (#46) Notice Domain 구현
  data/src/main/java/com/semicolon/data/remote/api/NoticesApi.kt
  data/src/main/java/com/semicolon/data/remote/response/notice/NoticeDetailResponse.kt
  domain/src/main/java/com/semicolon/domain/entity/notice/NoticeDetailEntity.kt
  domain/src/main/java/com/semicolon/domain/enum/NoticeType.kt
  domain/src/main/java/com/semicolon/domain/repository/NoticeRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/notice/FetchNoticeListUseCase.kt
Labels: 기능 추가

#62 🔀 :: (#55) exercise repository implementation
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  data/build.gradle.kts
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/exercise/WalkRecordEntity.kt
  data/src/main/java/com/semicolon/data/local/storage/ExerciseInfoDataStorage.kt
  data/src/main/java/com/semicolon/data/local/storage/ExerciseInfoDataStorageImpl.kt
  data/src/main/java/com/semicolon/data/remote/request/exercise/FinishMeasureExerciseRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/exercise/SendLocationRecordsRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/exercise/StartMeasureExerciseRequest.kt
  data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
  data/src/main/java/com/semicolon/data/util/UtilFunc.kt
  domain/src/main/java/com/semicolon/domain/enum/GoalType.kt
Labels: 기능 추가

#35 🔀 :: (#32) User Domain 구현 1
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  data/build.gradle.kts
  data/src/main/java/com/semicolon/data/local/converter/TypeConverters.kt
  data/src/main/java/com/semicolon/data/local/dao/UserDao.kt
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalUserDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/user/UserMyPageRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/user/UserOwnBadgeRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/user/UserProfileRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/api/UserApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/request/users/UserSignInRequest.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FetchMyPageResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FetchOwnBadgeResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FetchUserProfileResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/UserReissueResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/UserSignInResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/inquirymypage/InquiryMypageResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/inquirymypage/TitleBadge.kt
  data/src/main/java/com/semicolon/data/remote/response/users/inquiryownbadges/Badge.kt
  data/src/main/java/com/semicolon/data/remote/response/users/inquiryownbadges/InquiryOwnBadgeResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/userinquiryprofile/TitleBadge.kt
  data/src/main/java/com/semicolon/data/remote/response/users/userinquiryprofile/UserInquiryProfileResponse.kt
  data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/users/UserMyPageEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/users/UserOwnBadgeEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/users/UserProfileEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/users/UserSignInEntity.kt
  domain/src/main/java/com/semicolon/domain/param/user/PatchUserChangePasswordParam.kt
  domain/src/main/java/com/semicolon/domain/param/user/PostUserSignInParam.kt
  domain/src/main/java/com/semicolon/domain/param/user/PostUserSignUpParam.kt
  domain/src/main/java/com/semicolon/domain/param/user/VerifyPhoneNumberSignUpParam.kt
  domain/src/main/java/com/semicolon/domain/repository/UserRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FetchMypageUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FetchUserOwnBadgeUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FetchUserProfileUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/PatchUserChangePasswordUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/PostUserSignInUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/PostUserSignUpUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/VerifyUserPhoneNumberUseCase.kt
Labels: 기능 추가

#65 🔀 :: (#57) User Domain 구현 2
  domain/src/main/java/com/semicolon/domain/entity/users/FindUserAccountEntity.kt
  domain/src/main/java/com/semicolon/domain/param/user/PatchUserHealthParam.kt
  domain/src/main/java/com/semicolon/domain/param/user/SignUpClassParam.kt
  domain/src/main/java/com/semicolon/domain/param/user/UpdateProfileParam.kt
  domain/src/main/java/com/semicolon/domain/repository/UserRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FetchMypageUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FetchUserOwnBadgeUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FetchUserProfileUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FindUserAccountUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/PatchSchoolUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/PatchUserChangePasswordUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/PatchUserHealthUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/PostUserSignInUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/PostUserSignUpUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/SetBadgeUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/SignUpClassUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/UpdateProfileUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/VerifyUserPhoneNumberUseCase.kt
Labels: 기능 추가

#67 🔀 :: (#66) user data 로직 2
  data/src/main/java/com/semicolon/data/remote/api/UserApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/request/users/PatchUserHealthRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/users/SignUpClassRequest.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FindUserAccountResponse.kt
  data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/param/user/SignUpClassParam.kt
Labels: 기능 추가

#59 🔀 :: (#58) school logic
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSchoolDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSchoolDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/school/SearchSchoolResponse.kt
  data/src/main/java/com/semicolon/data/repository/SchoolRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/school/SearchSchoolEntity.kt
  domain/src/main/java/com/semicolon/domain/repository/SchoolRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/school/SearchSchoolUseCase.kt
Labels: 기능 추가

#71 🔀 :: (#68) 자동 로그인 로직 구현
  data/src/main/java/com/semicolon/data/local/datasource/LocalUserDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/storage/AuthDataStorage.kt
  data/src/main/java/com/semicolon/data/local/storage/AuthDataStorageImpl.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/users/UserSignInResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/UserSignUpResponse.kt
  data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/users/UserSignInEntity.kt
  domain/src/main/java/com/semicolon/domain/repository/UserRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/AutoLoginUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/PostUserSignInUseCase.kt
Labels: 기능 추가

#70 🔀 :: (#52) notification domain 로직 구현
  domain/src/main/java/com/semicolon/domain/entity/notification/NotificationEntity.kt
  domain/src/main/java/com/semicolon/domain/repository/NotificationRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/notification/.gitkeep
  domain/src/main/java/com/semicolon/domain/usecase/notification/FetchNotificationListUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/notification/ReadNotificationUseCase.kt
Labels: 기능 추가

#73 🔀 :: (#72) base
  presentation/src/main/java/com/semicolon/walkhub/ui/base/BaseActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/base/BaseFragment.kt
Labels: 프로젝트 설정

#85 🔀 :: (#84) colors
  presentation/src/main/res/values/colors.xml
Labels: 프로젝트 설정

#83 🔀 :: (#81) 참여한 챌린지 목록보기
  data/src/main/java/com/semicolon/data/remote/api/ChallengeApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteChallengeDateSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteChallengeDateSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/ChallengeRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/repository/ChallengeRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/challenge/FetchMyChallengesUseCase.kt
Labels: 기능 추가

#82 🔀 :: (#80) challenge 도메인 변경
  data/src/main/java/com/semicolon/data/local/entity/challenge/ChallengeAndDetail.kt
  data/src/main/java/com/semicolon/data/local/entity/challenge/ChallengeDetailRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/challenge/ChallengeParticipantRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/challenge/ChallengeRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/response/challenge/ChallengeDetailResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/challenge/ChallengeListResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/challenge/ChallengeParticipantListResponse.kt
  domain/src/main/java/com/semicolon/domain/entity/challenge/ChallengeDetailEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/challenge/ChallengeEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/challenge/ChallengeParticipantEntity.kt
  domain/src/main/java/com/semicolon/domain/enum/ChallengeGoalScope.kt
  domain/src/main/java/com/semicolon/domain/enum/ChallengeGoalType.kt
  domain/src/main/java/com/semicolon/domain/enum/ChallengeScope.kt
  domain/src/main/java/com/semicolon/domain/enum/ChallengeUserScope.kt
Labels: chore

#75 🔀 :: (#74) bottom navigation
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/semicolon/walkhub/ui/MainActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/challenge/ChallengeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/ProfileFragment.kt
  presentation/src/main/res/drawable-hdpi/ic_nav_challenge.png
  presentation/src/main/res/drawable-hdpi/ic_nav_home.png
  presentation/src/main/res/drawable-hdpi/ic_nav_hub.png
  presentation/src/main/res/drawable-hdpi/ic_nav_profile.png
  presentation/src/main/res/drawable-ldpi/ic_nav_challenge.png
  presentation/src/main/res/drawable-ldpi/ic_nav_home.png
  presentation/src/main/res/drawable-ldpi/ic_nav_hub.png
  presentation/src/main/res/drawable-ldpi/ic_nav_profile.png
  presentation/src/main/res/drawable-mdpi/ic_nav_challenge.png
  presentation/src/main/res/drawable-mdpi/ic_nav_home.png
  presentation/src/main/res/drawable-mdpi/ic_nav_hub.png
  presentation/src/main/res/drawable-mdpi/ic_nav_profile.png
  presentation/src/main/res/drawable-xhdpi/ic_nav_challenge.png
  presentation/src/main/res/drawable-xhdpi/ic_nav_home.png
  presentation/src/main/res/drawable-xhdpi/ic_nav_hub.png
  presentation/src/main/res/drawable-xhdpi/ic_nav_profile.png
  presentation/src/main/res/drawable-xxhdpi/ic_nav_challenge.png
  presentation/src/main/res/drawable-xxhdpi/ic_nav_home.png
  presentation/src/main/res/drawable-xxhdpi/ic_nav_hub.png
  presentation/src/main/res/drawable-xxhdpi/ic_nav_profile.png
  presentation/src/main/res/drawable-xxxhdpi/ic_nav_challenge.png
  presentation/src/main/res/drawable-xxxhdpi/ic_nav_home.png
  presentation/src/main/res/drawable-xxxhdpi/ic_nav_hub.png
  presentation/src/main/res/drawable-xxxhdpi/ic_nav_profile.png
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_challenge.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/fragment_hub.xml
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/menu/bottom_nav_menu.xml
  presentation/src/main/res/navigation/mobile_navigation.xml
Labels: 프로젝트 설정

#87 🔀 :: (#86) changes in exercise
  data/src/main/java/com/semicolon/data/background/worker/SynchronizeExerciseWorker.kt
  data/src/main/java/com/semicolon/data/remote/api/ExerciseApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteExerciseDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteExerciseDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/request/exercise/SaveDailyExerciseRequest.kt
  data/src/main/java/com/semicolon/data/remote/response/exercise/ExerciseAnalysisResultResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/exercise/ExerciseRecordListResponse.kt
  data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/exercise/ExerciseAnalysisResultEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/exercise/ExerciseRecordEntity.kt
  domain/src/main/java/com/semicolon/domain/repository/ExerciseRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchDailyExerciseRecordUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchExerciseAnalysisResultUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchExerciseRecordListUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/FinishMeasureExerciseUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/IsMeasuringUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/StartMeasureExerciseUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/StartRecordExerciseUseCase.kt
Labels: 기능 추가, chore

#91 🔀 :: (#90) test package 작성
  data/src/test/java/com/semicolon/data/ExampleUnitTest.kt
  data/src/test/java/com/semicolon/data/datasource/.gitkeep
  data/src/test/java/com/semicolon/data/repository/.gitkeep
  domain/src/test/java/com/semicolon/domain/ExampleUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/.gitkeep
Labels: 테스트 추가

#96 🔀 :: (#89) mockito kotlin setting 설정
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  data/build.gradle.kts
  domain/build.gradle.kts
Labels: 프로젝트 설정

#88 🔀 :: (#78) user update
  data/src/main/java/com/semicolon/data/local/converter/TypeConverters.kt
  data/src/main/java/com/semicolon/data/local/dao/UserDao.kt
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalUserDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/user/FetchCaloriesLevelRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/user/UserMyPageRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/user/UserOwnBadgeRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/user/UserProfileRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/api/UserApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/request/users/PatchDailyWalkGoalRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/users/UpdateProfileRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/users/UserChangePasswordRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/users/UserSignUpRequest.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FetchCaloriesLevelResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FetchMyPageResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FetchOwnBadgeResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FetchUserProfileResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/UserReissueResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/UserSignUpResponse.kt
  data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/users/FetchCaloriesLevelEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/users/UserMyPageEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/users/UserOwnBadgeEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/users/UserProfileEntity.kt
  domain/src/main/java/com/semicolon/domain/param/user/PatchDailyWalkGoalParam.kt
  domain/src/main/java/com/semicolon/domain/param/user/PatchUserChangePasswordParam.kt
  domain/src/main/java/com/semicolon/domain/param/user/PostUserSignUpParam.kt
  domain/src/main/java/com/semicolon/domain/param/user/SignUpClassParam.kt
  domain/src/main/java/com/semicolon/domain/param/user/UpdateProfileParam.kt
  domain/src/main/java/com/semicolon/domain/repository/UserRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FetchCaloriesLevelUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FetchUserOwnBadgeUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/PatchDailyWalkGoalUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/PatchSchoolUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/SetBadgeUseCase.kt
Labels: 기능 추가

#103 🔀 :: challenge repository toEntity 통일
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteChallengeDateSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteChallengeDateSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/ChallengeRepositoryImpl.kt
Labels: chore

#100 🔀 :: (#97) remote school data source test
  data/src/test/java/com/semicolon/data/datasource/RemoteSchoolDataSourceTest.kt
Labels: 테스트 추가

#106 🔀 :: (#93) test challenge repository
  data/src/test/java/com/semicolon/data/repository/.gitkeep
  data/src/test/java/com/semicolon/data/repository/ChallengeRepositoryUnitTest.kt
Labels: 테스트 추가

#101 🔀 :: (#99) LocalChallengeDataSource test
  data/src/test/java/com/semicolon/data/datasource/.gitkeep
  data/src/test/java/com/semicolon/data/datasource/LocalChallengeDataSourceUnitTest.kt
Labels: 테스트 추가

#109 🔀 :: (#94) test challenge usecase
  domain/src/test/java/com/semicolon/domain/usecase/.gitkeep
  domain/src/test/java/com/semicolon/domain/usecase/challenge/FetchChallengeDetailUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/challenge/FetchChallengeParticipantsUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/challenge/FetchChallengesUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/challenge/FetchMyChallengesUseCaseUnitCase.kt
  domain/src/test/java/com/semicolon/domain/usecase/challenge/PostParticipateChallengeUseCaseUnitTest.kt
Labels: 테스트 추가

#110 🔀 :: (#104) school repository test
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSchoolDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSchoolDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/SchoolRepositoryImpl.kt
  data/src/test/java/com/semicolon/data/datasource/RemoteSchoolDataSourceUnitTest.kt
  data/src/test/java/com/semicolon/data/repository/SchoolRepositoryUnitTest.kt
Labels: 테스트 추가

#114 🔀 :: (#112) search school use case unit test
  domain/src/test/java/com/semicolon/domain/usecase/school/SearchSchoolUseCaseUnitTest.kt
Labels: 테스트 추가

#116 🔀 :: (#111) user data source test
  data/src/test/java/com/semicolon/data/datasource/LocalUserDataSourceUnitTest.kt
  data/src/test/java/com/semicolon/data/datasource/RemoteUserDataSourceUnitTest.kt
Labels: 테스트 추가

#108 🔀 :: (#107) badge 구현
  data/src/main/java/com/semicolon/data/local/converter/TypeConverters.kt
  data/src/main/java/com/semicolon/data/local/dao/BadgeDao.kt
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalBadgeDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalBadgeDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/badge/FetchMyBadgesRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/badge/FetchNewBadgesRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/badge/FetchUserBadgesRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/api/BadgeApi.kt
  data/src/main/java/com/semicolon/data/remote/api/UserApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteBadgeDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteBadgeDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/badge/FetchMyBadgesResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/badge/FetchNewBadgesResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/badge/FetchUserBadgesResponse.kt
  data/src/main/java/com/semicolon/data/repository/BadgeRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/badge/FetchMyBadgesEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/badge/FetchNewBadgesEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/badge/FetchUserBadgesEntity.kt
  domain/src/main/java/com/semicolon/domain/repository/BadgeRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/badge/FetchMyBadgesUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/badge/FetchNewBadgesUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/badge/FetchUserBadgesUseCase.kt
Labels: 기능 추가

#129 🔀 :: (#126) user toEntity datasource
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
  data/src/test/java/com/semicolon/data/datasource/RemoteUserDataSourceUnitTest.kt
Labels: 리팩토링

#134 🔀 :: (#133) google oauth and permission
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/di/WalkHubApplication.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/login/LoginActivity.kt
  presentation/src/main/res/layout/activity_login.xml
Labels: 프로젝트 설정

#132 🔀 :: (#105) test exercise domain
  buildSrc/src/main/kotlin/Dependency.kt
  data/build.gradle.kts
  data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
  data/src/test/java/com/semicolon/data/repository/ExerciseRepositoryUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/exercise/FetchDailyExerciseRecordUseCaseTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/exercise/FetchExerciseAnalysisResultUseCaseTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/exercise/FetchExerciseRecordListUseCaseTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/exercise/FinishMeasureExerciseUseCaseTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/exercise/IsMeasuringUseCaseTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/exercise/StartMeasureExerciseUseCaseTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/exercise/StartRecordExerciseUseCaseTest.kt
Labels: 테스트 추가, 버그

#151 🔀 :: (#60) notice data 로직
  data/src/main/java/com/semicolon/data/local/converter/TypeConverters.kt
  data/src/main/java/com/semicolon/data/local/dao/NoticeDao.kt
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalNoticeDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalNoticeDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/notice/NoticeListRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/api/NoticesApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteNoticeDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteNoticeDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/notice/NoticeListResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/notice/NoticeWriter.kt
  data/src/main/java/com/semicolon/data/repository/NoticeRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/notice/NoticeEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/notice/NoticeWriterEntity.kt
  domain/src/main/java/com/semicolon/domain/enum/NoticeType.kt
  domain/src/main/java/com/semicolon/domain/repository/NoticeRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/notice/FetchNoticeListUseCase.kt
Labels: 리팩토링, 기능 추가, chore, 버그

#121 🔀 :: (#78) network_module
  presentation/src/main/java/com/semicolon/walkhub/di/NetWorkModule.kt
Labels: 기능 추가

#156 🔀 :: (#150) room module
  presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt
Labels: 기능 추가

#159 🔀 :: (#158) extension status bar
  presentation/src/main/java/com/semicolon/walkhub/util/View.kt
  presentation/src/main/res/values-night/styles.xml
  presentation/src/main/res/values/themes.xml
Labels: 프로젝트 설정

#162 🔀 :: (#161) event flow
  buildSrc/src/main/kotlin/Dependency.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/semicolon/walkhub/extensions/Lifecycle.kt
  presentation/src/main/java/com/semicolon/walkhub/extensions/View.kt
  presentation/src/main/java/com/semicolon/walkhub/util/EventFlow.kt
Labels: 프로젝트 설정

#69 🔀 :: (#61) notification data 로직 구현
  data/src/main/java/com/semicolon/data/local/dao/NotificationDao.kt
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalNotificationDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalNotificationDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/notification/NotificationRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/api/NotificationApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteNotificationDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteNotificationDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/notification/NotificationListResponse.kt
  data/src/main/java/com/semicolon/data/repository/NotificationRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/notice/NoticeEntity.kt
  domain/src/main/java/com/semicolon/domain/repository/NotificationRepository.kt
Labels: 기능 추가

#166 🔀 :: (#164) notice URL / 제거
  data/src/main/java/com/semicolon/data/remote/api/NotificationApi.kt
Labels: 버그

#165 🔀 :: (#163) notification URL / 제거
  data/src/main/java/com/semicolon/data/remote/api/NoticesApi.kt
Labels: 버그

#168 🔀 :: (#167) 병합 오류 수정
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
  domain/src/main/java/com/semicolon/domain/entity/notice/NoticeEntity.kt
Labels: 버그

#171 🔀 :: DataBase에 Rank부분 코드 작성
  data/src/main/java/com/semicolon/data/local/converter/RankListTypeConverter.kt
  data/src/main/java/com/semicolon/data/local/converter/TypeConverters.kt
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/OurSchoolUserRankRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/SchoolRankRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/SearchSchoolRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/SearchUserRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/UserRankRoomEntity.kt
Labels: 기능 추가

#173 🔀 :: (#160) add Room Dao
  presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt
Labels: 버그

#176 🔀 :: (#169) Rank interface url에서 /삭제
  data/src/main/java/com/semicolon/data/remote/api/RankApi.kt
Labels: chore

#177 🔀 :: (#172) datasource module
  presentation/src/main/java/com/semicolon/walkhub/di/LocalDataSourceModule.kt
  presentation/src/main/java/com/semicolon/walkhub/di/RemoteDataSourceModule.kt
  presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt
Labels: 기능 추가

#180 🔀:: (#178) repository module
  presentation/src/main/java/com/semicolon/walkhub/di/RepositoryModule.kt
Labels: 기능 추가

#182 🔀:: (#181) storage module
  presentation/src/main/java/com/semicolon/walkhub/di/StorageModule.kt
Labels: 기능 추가

#174 🔀 :: (#146) hub main ui
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/extensions/View.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSchoolRankRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/HubSchoolRank.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
  presentation/src/main/res/drawable-hdpi/bg_hub_edit_text.xml
  presentation/src/main/res/drawable-hdpi/bg_hub_my_school.xml
  presentation/src/main/res/drawable-mdpi/ic_hub_search.xml
  presentation/src/main/res/drawable/ic_back.xml
  presentation/src/main/res/drawable/ic_rank_first.xml
  presentation/src/main/res/drawable/ic_rank_second.xml
  presentation/src/main/res/drawable/ic_rank_third.xml
  presentation/src/main/res/drawable/ic_spinner_down.xml
  presentation/src/main/res/layout/fragment_hub.xml
  presentation/src/main/res/layout/hub_school_rank_view.xml
  presentation/src/main/res/navigation/mobile_navigation.xml
Labels: 기능 추가

#188 🔀 :: (#187) fix base
  presentation/src/main/java/com/semicolon/walkhub/ui/MainActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/base/BaseActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/base/BaseFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/challenge/ChallengeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/login/LoginActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/ProfileFragment.kt
Labels: 프로젝트 설정

#184 🔀 :: (#183) hilt error
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/semicolon/walkhub/di/NetWorkModule.kt
  presentation/src/main/java/com/semicolon/walkhub/di/RepositoryModule.kt
  presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt
Labels: 기능 추가

#189 🔀 :: (#185) hub main logic
  presentation/src/main/java/com/semicolon/walkhub/ui/MainActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/base/BaseActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/base/BaseFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/challenge/ChallengeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSchoolRankRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/HubSchoolRank.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/login/LoginActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/ProfileFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/HubMainViewModel.kt
  presentation/src/main/res/layout/fragment_hub.xml
  presentation/src/main/res/layout/hub_school_rank_view.xml
  presentation/src/main/res/layout/item_hub_main_spinner.xml
  presentation/src/main/res/values/array.xml
Labels: 기능 추가

#192 🔀 :: (#191) 유저랭킹조회 수정
  data/src/main/java/com/semicolon/data/remote/api/RankApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/RankRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/param/rank/FetchUserRankParam.kt
Labels: 리팩토링

#193 🔀:: (#155) badge remote datasource test
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteBadgeDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteBadgeDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/BadgeRepositoryImpl.kt
  data/src/test/java/com/semicolon/data/datasource/RemoteBadgeDataSourceUnitTest.kt
Labels: 리팩토링, 테스트 추가

#195 🔀 :: (#190) hub school ui
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSchoolRankRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSearchUserRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubViewPagerAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/OurSchoolUserRankData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/UserRankData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/UserRankRvData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubInfoFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubUserRankViewModel.kt
  presentation/src/main/res/layout/activity_hub_school.xml
  presentation/src/main/res/layout/fragment_hub_info.xml
  presentation/src/main/res/layout/fragment_hub_rank.xml
  presentation/src/main/res/layout/hub_user_search_view.xml
  presentation/src/main/res/menu/menu_hub_search.xml
Labels: 기능 추가

#198 🔀:: (#194) badge repository test
  data/src/test/java/com/semicolon/data/repository/BadgeRepositoryUnitTest.kt
Labels: 테스트 추가

#154 🔀 :: (#144) badge local datasource test
  data/src/test/java/com/semicolon/data/datasource/LocalBadgeDataSourceUnitTest.kt
Labels: 테스트 추가

#149 🔀 :: (#143) user usecase test
  domain/src/test/java/com/semicolon/domain/usecase/user/AutoLoginUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/user/FetchCaloriesLevelUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/user/FetchMyPageUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/user/FetchUserProfileUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/user/FindUserAccountUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/user/PatchDailyWalkGoalUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/user/PatchSchoolUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/user/PatchUserChangePasswordUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/user/PatchUserHealthUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/user/PostUserSignInUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/user/PostUserSignUpUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/user/SignUpClassUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/user/UpdateProfileUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/user/VerifyUserPhoneNumberUseCaseUnitTest.kt
Labels: 테스트 추가

#201 🔀 :: (#179) Register & Login 화면 구현
  presentation/src/main/java/com/semicolon/walkhub/ui/HomeActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/login/LoginActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/Register.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/SearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/agree/AgreeActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/agree/PrivacyActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/agree/ServiceInstructionActivity.kt
  presentation/src/main/res/drawable-ldpi/buttondesign.xml
  presentation/src/main/res/drawable-ldpi/cardviewdesign.xml
  presentation/src/main/res/drawable-ldpi/custom_checkbox.xml
  presentation/src/main/res/drawable-ldpi/edittextdesign.xml
  presentation/src/main/res/drawable-ldpi/mainbuttondesign.xml
  presentation/src/main/res/drawable-ldpi/notificationbutton.xml
  presentation/src/main/res/drawable-ldpi/photo.png
  presentation/src/main/res/drawable-ldpi/register_btn.xml
  presentation/src/main/res/drawable-ldpi/registerbuttondesign.xml
  presentation/src/main/res/drawable-ldpi/servicebutton.xml
  presentation/src/main/res/layout/activity_agree.xml
  presentation/src/main/res/layout/activity_home.xml
  presentation/src/main/res/layout/activity_login.xml
  presentation/src/main/res/layout/activity_privacy.xml
  presentation/src/main/res/layout/activity_register.xml
  presentation/src/main/res/layout/activity_search_school.xml
  presentation/src/main/res/layout/activity_serviceinstruction.xml
Labels: 기능 추가

#225 🔀 :: (#223) circular progress bar
  presentation/src/main/java/com/semicolon/walkhub/bindingadapter/CircularProgressBarAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/customview/CircularProgressBar.kt
  presentation/src/main/res/layout/example_progress.xml
Labels: 기능 추가

#202 🔀 :: (#196) hub fragment UI
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSchoolRankRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/HubSchoolRank.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubInfoFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubUserRankViewModel.kt
  presentation/src/main/res/drawable-v24/bg_primary_button.xml
  presentation/src/main/res/layout/activity_hub_school.xml
  presentation/src/main/res/layout/fragment_hub_info.xml
  presentation/src/main/res/layout/fragment_hub_rank.xml
Labels: 기능 추가

#227 🔀:: (#209) badge usecase test
  domain/src/test/java/com/semicolon/domain/usecase/badge/FetchMyBadgesUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/badge/FetchNewBadgesUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/badge/FetchUserBadgesUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/badge/SetBadgeUseCaseUnitTest.kt
Labels: 테스트 추가

#231 🔀 :: (#200) Level Domain
  domain/src/main/java/com/semicolon/domain/entity/level/LevelEntity.kt
  domain/src/main/java/com/semicolon/domain/repository/LevelRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/level/FetchLevelListUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/level/PatchMaxLevelUseCase.kt
Labels: 기능 추가

#234 🔀 :: (#233) Level Data
  data/src/main/java/com/semicolon/data/local/dao/LevelDao.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalLevelDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalLevelDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/level/LevelRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/api/LevelApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteLevelDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteLevelDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/level/LevelListResponse.kt
  data/src/main/java/com/semicolon/data/repository/LevelRepositoryImpl.kt
Labels: 기능 추가

#235 🔀 :: (#222) authorization interceptor
  data/src/main/java/com/semicolon/data/interceptor/AuthorizationInterceptor.kt
  presentation/src/main/java/com/semicolon/walkhub/di/NetWorkModule.kt
Labels: 기능 추가, chore

#136 🔀 :: (#29) FCM 설정
  .gitignore
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  domain/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/fcm/FCMManager.kt
Labels: 프로젝트 설정

#240 🔀 :: (#239) strange code
  buildSrc/src/main/kotlin/Dependency.kt
  presentation/src/main/java/com/semicolon/walkhub/di/NetWorkModule.kt
  presentation/src/main/java/com/semicolon/walkhub/fcm/FCMManager.kt
Labels: chore, 버그

#253 🔀 :: (#252) add ignore cases in authorization interceptor
  data/src/main/java/com/semicolon/data/interceptor/AuthorizationInterceptor.kt
Labels: chore

#246 🔀 :: (#245) 마이페이지 UI 구현
  presentation/src/main/res/layout/fragment_profile.xml
Labels: 기능 추가

#257 🔀 :: (#220) socket
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  data/build.gradle.kts
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSocketDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSocketDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/SocketRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/repository/SocketRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/socket/CheeringUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/socket/ConnectedSocketUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/socket/DisconnectedSocketUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/semicolon/walkhub/di/NetWorkModule.kt
  presentation/src/main/java/com/semicolon/walkhub/di/RemoteDataSourceModule.kt
  presentation/src/main/java/com/semicolon/walkhub/di/RepositoryModule.kt
Labels: 기능 추가

#210 🔀 :: (#147) Fragment Main XML 구현
  presentation/src/main/res/layout/fragment_home.xml
Labels: 기능 추가

#250 🔀 :: (#247) 설정 UI 구현
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/SettingFragment.kt
  presentation/src/main/res/layout/fragment_setting.xml
Labels: 기능 추가
