Repository Walkhub/walkhub_android, pull requests merged in 2022-03, with the labels that each got.

#272 🔀 :: (#260) add exercise business logic
  data/src/main/java/com/semicolon/data/local/dao/LocationRecordDao.kt
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/exercise/LocationRecordRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/storage/ExerciseInfoDataStorage.kt
  data/src/main/java/com/semicolon/data/local/storage/ExerciseInfoDataStorageImpl.kt
  data/src/main/java/com/semicolon/data/local/storage/FitnessAccumulateDataStorage.kt
  data/src/main/java/com/semicolon/data/local/storage/FitnessAccumulateDataStorageImpl.kt
  data/src/main/java/com/semicolon/data/local/storage/FitnessDataStorageImpl.kt
  data/src/main/java/com/semicolon/data/local/storage/SpeedDataStorage.kt
  data/src/main/java/com/semicolon/data/local/storage/SpeedDataStorageImpl.kt
  data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/exercise/ExerciseEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/exercise/GoalEntity.kt
  domain/src/main/java/com/semicolon/domain/enum/GoalType.kt
  domain/src/main/java/com/semicolon/domain/enum/MeasuringState.kt
  domain/src/main/java/com/semicolon/domain/repository/ExerciseRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchCurrentSpeedUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchGoalUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchMeasuredExerciseRecordUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchMeasuredTimeUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/IsMeasuringUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/PauseMeasureExerciseUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/ResumeMeasureExerciseUseCase.kt
  presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt
  presentation/src/main/java/com/semicolon/walkhub/di/StorageModule.kt
Labels: 기능 추가

#274 🔀 :: (#273) package name enum -> enums
  data/src/main/java/com/semicolon/data/local/dao/NoticeDao.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalNoticeDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalNoticeDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/challenge/ChallengeAndDetail.kt
  data/src/main/java/com/semicolon/data/local/entity/challenge/ChallengeDetailRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/challenge/ChallengeRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/storage/ExerciseInfoDataStorage.kt
  data/src/main/java/com/semicolon/data/local/storage/ExerciseInfoDataStorageImpl.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteNoticeDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteNoticeDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/challenge/ChallengeDetailResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/challenge/ChallengeListResponse.kt
  data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
  data/src/main/java/com/semicolon/data/repository/NoticeRepositoryImpl.kt
  data/src/main/java/com/semicolon/data/repository/RankRepositoryImpl.kt
  data/src/test/java/com/semicolon/data/datasource/LocalChallengeDataSourceUnitTest.kt
  data/src/test/java/com/semicolon/data/repository/ChallengeRepositoryUnitTest.kt
  data/src/test/java/com/semicolon/data/repository/ExerciseRepositoryUnitTest.kt
  domain/src/main/java/com/semicolon/domain/entity/challenge/ChallengeDetailEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/challenge/ChallengeEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/exercise/GoalEntity.kt
  domain/src/main/java/com/semicolon/domain/enums/ChallengeGoalScope.kt
  domain/src/main/java/com/semicolon/domain/enums/ChallengeGoalType.kt
  domain/src/main/java/com/semicolon/domain/enums/ChallengeUserScope.kt
  domain/src/main/java/com/semicolon/domain/enums/DateType.kt
  domain/src/main/java/com/semicolon/domain/enums/GoalType.kt
  domain/src/main/java/com/semicolon/domain/enums/MeasuringState.kt
  domain/src/main/java/com/semicolon/domain/enums/MoreDateType.kt
  domain/src/main/java/com/semicolon/domain/enums/NoticeType.kt
  domain/src/main/java/com/semicolon/domain/enums/RankScope.kt
  domain/src/main/java/com/semicolon/domain/param/exercise/StartMeasureExerciseParam.kt
  domain/src/main/java/com/semicolon/domain/param/rank/FetchOurSchoolUserRankParam.kt
  domain/src/main/java/com/semicolon/domain/param/rank/FetchUserRankParam.kt
  domain/src/main/java/com/semicolon/domain/param/rank/SearchSchoolParam.kt
  domain/src/main/java/com/semicolon/domain/param/rank/SearchUserParam.kt
  domain/src/main/java/com/semicolon/domain/repository/ExerciseRepository.kt
  domain/src/main/java/com/semicolon/domain/repository/NoticeRepository.kt
  domain/src/main/java/com/semicolon/domain/repository/RankRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/IsMeasuringUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/notice/FetchNoticeListUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/rank/FetchSchoolRankUseCase.kt
  domain/src/test/java/com/semicolon/domain/usecase/challenge/FetchChallengeDetailUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/challenge/FetchChallengesUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/challenge/FetchMyChallengesUseCaseUnitCase.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchSchoolViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchUserViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubUserViewModel.kt
Labels: chore, 버그

#278 🔀 :: (#275)measure home viewmodel
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/measure/MeasureHomeViewModel.kt
Labels: 기능 추가

#280 🔀 :: (#279) Level Di & error
  data/src/main/java/com/semicolon/data/local/dao/LevelDao.kt
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
  presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt
Labels: chore

#281 🔀 :: (#267) MainFragment ViewModel 및 서버 연동 구현
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/OurSchoolUserRankRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/OurSchoolUserRankResponse.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/OurSchoolUserRankEntity.kt
  domain/src/main/java/com/semicolon/domain/enums/DateType.kt
  domain/src/main/java/com/semicolon/domain/enums/RankScope.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/home/model/HomeData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/home/model/RankData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/MySchoolUserRankData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/login/LoginActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/home/HomeViewModel.kt
  presentation/src/main/res/layout/fragment_home.xml
Labels: 기능 추가

#283 🔀 :: (#282) recycler view adapter
  presentation/src/main/java/com/semicolon/walkhub/adapter/BindingViewHolder.kt
  presentation/src/main/java/com/semicolon/walkhub/adapter/RecyclerViewAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/adapter/RecyclerViewItem.kt
Labels: 기능 추가

#217 🔀 :: (#216) 건강 정보 입력 XML & 뷰 기능
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/ui/register/ScanHealthInformationActivity.kt
  presentation/src/main/res/layout/activity_scan_health_information.xml
Labels: 기능 추가

#295 🔀:: (#285) measure viewmodel
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/measure/MeasureViewModel.kt
Labels: 기능 추가

#290 🔀 :: (#289) 프래그먼트에서 세팅 액티비티로 수정
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/SettingActivity.kt
  presentation/src/main/res/layout/activity_setting.xml
Labels: chore

#276 🔀 :: (#264) 건강정보 수정 UI 작성
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ModifyHealthInfoFragment.kt
  presentation/src/main/res/drawable/girl_btn.xml
  presentation/src/main/res/drawable/modify_health_edit_back.xml
  presentation/src/main/res/layout/fragment_modify_health_info.xml
Labels: 기능 추가

#284 🔀 :: (#265) LoginViewModel
  presentation/src/main/java/com/semicolon/walkhub/ui/login/LoginActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/login/LoginViewModel.kt
  presentation/src/main/res/layout/activity_login.xml
Labels: 기능 추가

#296 🔀 :: (#232) activity analysis viewmodel
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/ui/analysis/ActivityAnalysis.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/analysis/ActivityAnalysisActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/analysis/WalkGraph.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/analysis/ActivityAnalysisViewModel.kt
Labels: 기능 추가

#298 🔀 :: (#297) connect main and analysis
  presentation/src/main/java/com/semicolon/walkhub/ui/analysis/ActivityAnalysis.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/analysis/AppBar.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/home/HomeViewModel.kt
Labels: chore

#288 🔀 :: (#286) 마이페이지에 gravity부여
  presentation/src/main/res/layout/fragment_profile.xml
Labels: chore

#301 🔀 :: (#294) 세팅 뷰기능 추가
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/SettingActivity.kt
  presentation/src/main/res/layout/activity_setting.xml
Labels: 기능 추가

#292 🔀 :: (#291) 마이페이지 뷰기능 구현
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/ProfileFragment.kt
Labels: 기능 추가

#302 🔀 :: (#299) modify activity main UI
  presentation/src/main/res/drawable/background_home.jpg
  presentation/src/main/res/drawable/logo_ok.png
  presentation/src/main/res/layout/activity_home.xml
Labels: chore

#309 🔀 :: (#300) hub viewmodel 구현
  data/src/main/java/com/semicolon/data/local/entity/rank/SchoolRankRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/api/RankApi.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/inquiryRank/school/SchoolRankResponse.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/SchoolRankEntity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSearchSchoolRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/HubSchoolRankData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchSchoolViewModel.kt
  presentation/src/main/res/layout/activity_hub_search_school.xml
  presentation/src/main/res/layout/fragment_hub.xml
Labels: 기능 추가

#249 🔀 :: (#248) sign up class ui
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/SignUpClassActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/SettingActivity.kt
  presentation/src/main/res/drawable/bg_primary_button_off.xml
  presentation/src/main/res/drawable/bg_sign_up_class_et.xml
  presentation/src/main/res/layout/activity_setting.xml
  presentation/src/main/res/layout/activity_sign_up_class.xml
  presentation/src/main/res/values/colors.xml
Labels: 기능 추가

#293 🔀 :: (#256) hub search
  domain/src/main/java/com/semicolon/domain/param/rank/FetchOurSchoolUserRankParam.kt
  domain/src/main/java/com/semicolon/domain/param/rank/FetchUserRankParam.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/analysis/DebouncedTextInputEditText.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchUserViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubUserViewModel.kt
  presentation/src/main/res/menu/menu_hub_search.xml
Labels: 기능 추가

#311 🔀 :: (#305) modify bottom navigation
  presentation/src/main/res/color/selector_bnv_menu.xml
  presentation/src/main/res/drawable/background_home.jpg
  presentation/src/main/res/drawable/ic_calories.png
  presentation/src/main/res/drawable/ic_challenge.png
  presentation/src/main/res/drawable/ic_clock.png
  presentation/src/main/res/drawable/ic_distance.png
  presentation/src/main/res/drawable/ic_home.png
  presentation/src/main/res/drawable/ic_hub.png
  presentation/src/main/res/drawable/ic_profile.png
  presentation/src/main/res/drawable/logo_ok.png
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/menu/bottom_nav_menu.xml
Labels: chore

#315 🔀 :: (#314) change token logic & interceptor
  data/src/main/java/com/semicolon/data/interceptor/AuthorizationInterceptor.kt
  domain/src/main/java/com/semicolon/domain/exception/user/NeedLoginException.kt
Labels: chore

#254 🔀 :: (#251) 알림설정 UI 작성
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/NoticeSettingActivity.kt
  presentation/src/main/res/layout/activity_notice_setting.xml
Labels: 기능 추가

#263 🔀 :: (#262) 계정 정보 UI 구현
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/AccountInfoFragment.kt
  presentation/src/main/res/layout/fragment_account_info.xml
Labels: 기능 추가

#322 🔀 :: (#321) hub 자잘한 기능 구현
  data/src/main/java/com/semicolon/data/local/entity/rank/OurSchoolUserRankRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/OurSchoolUserRankResponse.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/OurSchoolUserRankEntity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/MySchoolUserRankData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubInfoFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchUserViewModel.kt
  presentation/src/main/res/drawable/progress_horizontal.xml
  presentation/src/main/res/layout/activity_hub_school.xml
  presentation/src/main/res/layout/activity_sign_up_class.xml
  presentation/src/main/res/layout/fragment_hub.xml
  presentation/src/main/res/layout/fragment_hub_rank.xml
  presentation/src/main/res/layout/hub_school_rank_view.xml
  presentation/src/main/res/layout/hub_user_search_view.xml
  presentation/src/main/res/layout/item_hub_main_spinner.xml
  presentation/src/main/res/values/strings.xml
Labels: 기능 추가

#330 🔀 :: (#328) user 새로운 기능 추가
  data/src/main/java/com/semicolon/data/local/dao/UserDao.kt
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalUserDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/user/FetchAuthInfoRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/user/FetchDailyGoalRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/user/FetchInfoRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/user/FetchUserHealthRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/user/UserMyPageRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FetchAuthInfoResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FetchDailyGoalResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FetchInfoResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FetchUserHealthResponse.kt
  data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/users/FetchAuthInfoEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/users/FetchDailyGoalEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/users/FetchInfoEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/users/FetchUserHealthEntity.kt
  domain/src/main/java/com/semicolon/domain/repository/UserRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/ChangeIndependenceUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/CheckAccountOverlapUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/CheckClassCodeUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/DeleteAccountUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/DeleteClassUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FetchAuthInfoUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FetchDailyGoalUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FetchInfoUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/FetchUserHealthUseCase.kt
Labels: 기능 추가

#320 🔀 :: (#316) splash
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/SettingActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/splash/Splash.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/splash/SplashActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/splash/SplashViewModel.kt
  presentation/src/main/res/values/themes.xml
Labels: 기능 추가

#329 🔀 :: (#326) 랭크 로직 수정
  data/src/main/java/com/semicolon/data/remote/api/RankApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/inquiryRank/user/UserRankResponse.kt
  data/src/main/java/com/semicolon/data/repository/RankRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/UserRankEntity.kt
  domain/src/main/java/com/semicolon/domain/param/rank/SearchSchoolParam.kt
  domain/src/main/java/com/semicolon/domain/param/rank/SearchUserParam.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/ProfileFragment.kt
Labels: 리팩토링

#334 🔀 :: (#333) rank 명세서 따라 미수정 부분 수정
  data/src/main/java/com/semicolon/data/local/entity/rank/UserRankRoomEntity.kt
  domain/src/main/java/com/semicolon/domain/enums/DateType.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/SchoolUserRankData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/ProfileFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchSchoolViewModel.kt
Labels: chore

#335 🔀 :: (#331) 잔오류들 수정
  presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/SettingActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/home/HomeViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchSchoolViewModel.kt
Labels: chore

#338 🔀 :: (#336) measure exercise logic
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/storage/SpeedDataStorageImpl.kt
  data/src/main/java/com/semicolon/data/remote/request/exercise/FinishMeasureExerciseRequest.kt
  data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/enums/GoalType.kt
Labels: 기능 추가

#343 🔀 :: (#337) uncaught exception handler
  data/src/main/java/com/semicolon/data/util/HttpHandler.kt
  presentation/src/main/java/com/semicolon/walkhub/di/WalkHubApplication.kt
  presentation/src/main/java/com/semicolon/walkhub/util/WalkhubExceptionHandler.kt
Labels: 기능 추가

#342 🔀 :: (#339) new exercise api
  data/src/main/java/com/semicolon/data/remote/api/ExerciseApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteExerciseDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteExerciseDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/exercise/ExercisingUserListResponse.kt
  data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/exercise/ExercisingUserEntity.kt
  domain/src/main/java/com/semicolon/domain/repository/ExerciseRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchExercisingUserListUseCase.kt
Labels: 기능 추가

#345 🔀 :: (#344) fix wrong import
  presentation/src/main/java/com/semicolon/walkhub/util/WalkhubExceptionHandler.kt
Labels: 버그

#349 🔀::(#348) test bug
  data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
  data/src/test/java/com/semicolon/data/datasource/LocalUserDataSourceUnitTest.kt
  data/src/test/java/com/semicolon/data/datasource/RemoteUserDataSourceUnitTest.kt
  data/src/test/java/com/semicolon/data/repository/ExerciseRepositoryUnitTest.kt
  data/src/test/java/com/semicolon/data/repository/UserRepositoryUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/exercise/IsMeasuringUseCaseTest.kt
Labels: 버그

#350 🔀 :: (#268) measure home UI
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/bindingadapter/ImageBindingAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/bindingadapter/RecyclerViewBindingAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/measure/MeasureHomeActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/measure/MeasuringActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/util/UriParser.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/measure/MeasureHomeViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/measure/MeasureViewModel.kt
  presentation/src/main/res/drawable-xxhdpi/background_home.jpg
  presentation/src/main/res/drawable-xxhdpi/logo_ok.png
  presentation/src/main/res/drawable/bg_measure_home.xml
  presentation/src/main/res/drawable/ic_measure_arrow.xml
  presentation/src/main/res/drawable/ic_measuring_finish.xml
  presentation/src/main/res/drawable/ic_measuring_lock.xml
  presentation/src/main/res/drawable/ic_measuring_pause.xml
  presentation/src/main/res/drawable/ic_measuring_un_lock.xml
  presentation/src/main/res/drawable/ic_play_measure.xml
  presentation/src/main/res/drawable/img_cheering.png
  presentation/src/main/res/drawable/measuring_progressbar.xml
  presentation/src/main/res/layout/activity_measure_home.xml
  presentation/src/main/res/layout/activity_measuring.xml
  presentation/src/main/res/layout/item_measure_home_header.xml
  presentation/src/main/res/layout/item_measure_home_header_record.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/themes.xml
Labels: 기능 추가

#347 🔀 :: (#346) set up CI
  .github/workflows/ci.yml
  build.gradle.kts
  domain/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
Labels: 프로젝트 설정

#318 🔀 :: (#317) 마이페이지 로직 수정
  data/src/main/java/com/semicolon/data/remote/response/users/FetchMyPageResponse.kt
Labels: 리팩토링

#319 🔀 :: (#310) 마이페이지 ViewModel 구현
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/model/MyPageData.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/ProfileViewModel.kt
Labels: 기능 추가

#352 🔀::(#266) socket bug
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSocketDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteSocketDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/SocketRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/repository/SocketRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/socket/CheeringUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/socket/ReceiveCheeringUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/socket/ReceiveErrorUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/di/NetWorkModule.kt
  presentation/src/main/java/com/semicolon/walkhub/di/RemoteDataSourceModule.kt
  presentation/src/main/java/com/semicolon/walkhub/di/RepositoryModule.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
Labels: 버그

#356 🔀 :: (#214) 회원가입 단 학교 찾기
  data/src/main/java/com/semicolon/data/remote/api/RankApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/RankRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/param/rank/SearchSchoolParam.kt
  domain/src/main/java/com/semicolon/domain/repository/RankRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/rank/SearchSchoolUseCase.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/SearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/adapter/SearchSchoolAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/model/SecondSearchSchoolData.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/ui/AgreeActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/ui/PrivacyActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/ui/Register.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/ui/ServiceInstructionActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/register/SearchSchoolViewModel.kt
  presentation/src/main/res/layout/activity_search_school.xml
  presentation/src/main/res/layout/schoolitem.xml
Labels: 기능 추가

#358 353 Challenge Entity 변경
  data/src/main/java/com/semicolon/data/local/converter/TypeConverters.kt
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
  data/src/main/java/com/semicolon/data/local/entity/challenge/ChallengeParticipantRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/challenge/ChallengeRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/response/challenge/ChallengeListResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/challenge/ChallengeParticipantListResponse.kt
  data/src/test/java/com/semicolon/data/datasource/LocalChallengeDataSourceUnitTest.kt
  data/src/test/java/com/semicolon/data/datasource/RemoteChallengeDatasourceUnitTest.kt
  data/src/test/java/com/semicolon/data/repository/ChallengeRepositoryUnitTest.kt
  domain/src/androidTest/java/com/semicolon/domain/ExampleInstrumentedTest.kt
  domain/src/main/java/com/semicolon/domain/entity/challenge/ChallengeEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/challenge/ChallengeParticipantEntity.kt
  domain/src/test/java/com/semicolon/domain/usecase/challenge/FetchChallengesUseCaseUnitTest.kt
  domain/src/test/java/com/semicolon/domain/usecase/challenge/FetchMyChallengesUseCaseUnitCase.kt
Labels: chore

#362 🔀 :: (#361) challenge di 오류 해결
  presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt
Labels: 버그

#360 🔀 :: (#359) SeachSchoolViewModel hub와 회원가입 분리
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/SearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/adapter/SearchSchoolAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/register/model/SecondSearchSchoolData.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/SearchSchoolViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchSchoolViewModel.kt
Labels: chore

#304 🔀 :: (#303) 설정 뷰작동 업데이트
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/SettingActivity.kt
  presentation/src/main/res/layout/activity_setting.xml
  presentation/src/main/res/layout/fragment_modify_health_info.xml
Labels: 기능 추가

#366 🔀 :: (#357) update CD
  .github/workflows/cd.yml
Labels: 프로젝트 설정

#371 🔀 :: (#364) users update
  data/src/main/java/com/semicolon/data/local/entity/badge/FetchMyBadgesRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/user/UserMyPageRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/user/UserProfileRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/api/UserApi.kt
  data/src/main/java/com/semicolon/data/remote/request/users/CheckPhoneNumberRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/users/VerifyPhoneNumberSignUpRequest.kt
  data/src/main/java/com/semicolon/data/remote/response/badge/FetchMyBadgesResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/badge/FetchNewBadgesResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FetchMyPageResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FetchUserProfileResponse.kt
  data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
  data/src/test/java/com/semicolon/data/datasource/LocalUserDataSourceUnitTest.kt
  data/src/test/java/com/semicolon/data/datasource/RemoteUserDataSourceUnitTest.kt
  data/src/test/java/com/semicolon/data/repository/UserRepositoryUnitTest.kt
  domain/src/main/java/com/semicolon/domain/entity/badge/FetchMyBadgesEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/users/UserMyPageEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/users/UserProfileEntity.kt
  domain/src/main/java/com/semicolon/domain/param/user/VerifyPhoneNumberSignUpParam.kt
Labels: 기능 추가
