Repository Walkhub/walkhub_android, pull requests merged in 2022-05, with the labels that each got.

#457 🔀 :: (#456) cheering bug
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubUserViewModel.kt
Labels: chore, 버그

#467 🔀 :: (#406) 건강정보 수정 구현
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/ModifyHealthInfoActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/ModifyProfileActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/setting/ModifyHealthInfoViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/setting/NoticeSettingViewModel.kt
  presentation/src/main/res/layout/activity_modify_health_info.xml
  presentation/src/main/res/layout/activity_modify_profile.xml
  presentation/src/main/res/layout/fragment_profile.xml
Labels: 기능 추가

#466 🔀 :: (#458) 비밀번호 변경 구현
  data/src/main/java/com/semicolon/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/com/semicolon/data/remote/api/UserApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/request/users/CheckPasswordRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/users/UserChangePasswordRequest.kt
  data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
  data/src/test/java/com/semicolon/data/datasource/RemoteUserDataSourceUnitTest.kt
  data/src/test/java/com/semicolon/data/repository/UserRepositoryUnitTest.kt
  domain/src/main/java/com/semicolon/domain/param/user/PatchUserChangePasswordParam.kt
  domain/src/main/java/com/semicolon/domain/param/user/VerifyPasswordParam.kt
  domain/src/main/java/com/semicolon/domain/repository/UserRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/user/VerifyPasswordUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/AccountInfoActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/ChangePwActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ui/RealChangePwActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/setting/AccountInfoViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/setting/ChangePwViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/profile/setting/RealChangePwViewModel.kt
  presentation/src/main/res/layout/activity_change_pw.xml
  presentation/src/main/res/layout/activity_real_change_pw.xml
Labels: 기능 추가

#470 🔀 :: (#461) hub board error
  data/src/main/java/com/semicolon/data/local/entity/notice/NoticeListRoomEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/rank/OurSchoolUserRankRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteNoticeDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteNoticeDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/notice/NoticeListResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/OurSchoolUserRankResponse.kt
  data/src/main/java/com/semicolon/data/repository/NoticeRepositoryImpl.kt
  domain/src/main/java/com/semicolon/domain/entity/notice/NoticeEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/rank/OurSchoolUserRankEntity.kt
  domain/src/main/java/com/semicolon/domain/param/notice/FetchNoticeListParam.kt
  domain/src/main/java/com/semicolon/domain/repository/NoticeRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/notice/FetchNoticeListUseCase.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubInfoViewModel.kt
  presentation/src/main/res/layout/fragment_hub_info.xml
Labels: 버그

#473 🔀 :: (#471) hub error
  data/src/main/java/com/semicolon/data/local/entity/school/SchoolDetailRoomEntity.kt
  data/src/main/java/com/semicolon/data/remote/api/RankApi.kt
  domain/src/main/java/com/semicolon/domain/entity/school/SchoolDetailEntity.kt
  presentation/src/main/java/com/semicolon/walkhub/bindingadapter/ExerciseBindingAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/bindingadapter/HubBindingAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSchoolRankRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSearchSchoolRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSearchUserRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubInfoFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/SignUpClassActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubInfoViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchUserViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubUserViewModel.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/SignUpClassViewModel.kt
  presentation/src/main/res/layout/activity_hub_search_school.xml
  presentation/src/main/res/layout/fragment_hub_info.xml
  presentation/src/main/res/layout/fragment_hub_rank.xml
  presentation/src/main/res/layout/item_hub_search_user.xml
Labels: 버그

#476 🔀 :: (#441) refactor exercise business logic
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/storage/FitnessDataStorage.kt
  data/src/main/java/com/semicolon/data/local/storage/FitnessDataStorageImpl.kt
Labels: 리팩토링

#475 🔀 :: (#474) calorie level
  data/src/main/java/com/semicolon/data/remote/api/LevelApi.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/analysis/ActivityAnalysis.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/home/HomeViewModel.kt
Labels: 기능 추가

#478 🔀 :: (#477) patch badge error
  presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
Labels: 버그

#480 🔀 :: (#479) measure exercise crash
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/storage/FitnessDataStorageImpl.kt
Labels: 버그

#481 🔀 :: (#459) google fit permission check
  presentation/src/main/java/com/semicolon/walkhub/ui/HomeActivity.kt
Labels: chore, 버그

#484 🔀 :: (#483) location history
  data/src/main/AndroidManifest.xml
  data/src/main/java/com/semicolon/data/background/task/ExerciseBackgroundTask.kt
  data/src/main/java/com/semicolon/data/background/task/ExerciseBackgroundTaskImpl.kt
  data/src/main/java/com/semicolon/data/background/worker/CustomWorkerFactory.kt
  data/src/main/java/com/semicolon/data/background/worker/LocationTrackingWorker.kt
  data/src/main/java/com/semicolon/data/background/worker/SynchronizeExerciseWorkerFactory.kt
  data/src/main/java/com/semicolon/data/local/dao/LocationRecordDao.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
  data/src/main/res/drawable/logo_ok.png
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/di/WalkHubApplication.kt
Labels: chore, 버그

#485 🔀 :: (#482) hub refactor & fix bug
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSchoolRankRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSearchSchoolRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSearchUserRvAdapter.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubInfoFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSearchSchoolActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/SignUpClassActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/util/HubIntentKey.kt
  presentation/src/main/res/values/strings.xml
Labels: 리팩토링, 버그

#487 🔀 :: (#486) 마이페이지 뷰 수정
  presentation/src/main/java/com/semicolon/walkhub/ui/profile/ProfileFragment.kt
  presentation/src/main/res/layout/fragment_profile.xml
Labels: 기능 추가

#489 🔀 :: (#396) auto login logic
  data/src/main/java/com/semicolon/data/local/storage/AuthDataStorageImpl.kt
  data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
Labels: 기능 추가, chore

#493 🔀 :: (#491) modify rest api
  data/src/main/java/com/semicolon/data/remote/api/ExerciseApi.kt
  data/src/main/java/com/semicolon/data/remote/request/exercise/SendLocationRecordsRequest.kt
Labels: chore

#494 🔀 :: (#492) no dark mode
  presentation/src/main/java/com/semicolon/walkhub/di/WalkHubApplication.kt
Labels: chore

#497 🔀 :: (#496) wrong calorie
  data/src/main/java/com/semicolon/data/local/storage/FitnessDataStorageImpl.kt
Labels: chore
