Repository Walkhub/walkhub_android, pull requests merged in 2022-01, with the labels that each got.

#2 🔀 :: (#1) set package structure
  data/src/main/java/com/semicolon/data/local/dao/.gitkeep
  data/src/main/java/com/semicolon/data/local/database/.gitkeep
  data/src/main/java/com/semicolon/data/local/datasource/.gitkeep
  data/src/main/java/com/semicolon/data/local/entity/.gitkeep
  data/src/main/java/com/semicolon/data/remote/api/.gitkeep
  data/src/main/java/com/semicolon/data/remote/datasource/.gitkeep
  data/src/main/java/com/semicolon/data/remote/request/.gitkeep
  data/src/main/java/com/semicolon/data/remote/response/.gitkeep
  data/src/main/java/com/semicolon/data/repository/.gitkeep
  data/src/main/java/com/semicolon/data/util/.gitkeep
  domain/src/main/java/com/semicolon/domain/entity/.gitkeep
  domain/src/main/java/com/semicolon/domain/exception/.gitkeep
  domain/src/main/java/com/semicolon/domain/repository/.gitkeep
  domain/src/main/java/com/semicolon/domain/usecase/challenge/.gitkeep
  domain/src/main/java/com/semicolon/domain/usecase/exercise/.gitkeep
  domain/src/main/java/com/semicolon/domain/usecase/image/.gitkeep
  domain/src/main/java/com/semicolon/domain/usecase/notice/.gitkeep
  domain/src/main/java/com/semicolon/domain/usecase/notification/.gitkeep
  domain/src/main/java/com/semicolon/domain/usecase/rank/.gitkeep
  domain/src/main/java/com/semicolon/domain/usecase/school/.gitkeep
  domain/src/main/java/com/semicolon/domain/usecase/teacher/.gitkeep
  domain/src/main/java/com/semicolon/domain/usecase/user/.gitkeep
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/semicolon/walkhub/di/.gitkeep
  presentation/src/main/java/com/semicolon/walkhub/ui/MainActivity.kt
  presentation/src/main/java/com/semicolon/walkhub/util/.gitkeep
  presentation/src/main/java/com/semicolon/walkhub/viewmodel/.gitkeep
  presentation/src/main/res/layout/activity_main.xml
Labels: 프로젝트 설정

#4 🔀 :: (#3) business logic utility
  data/src/main/java/com/semicolon/data/util/.gitkeep
  data/src/main/java/com/semicolon/data/util/OfflineCacheUtil.kt
  domain/src/main/java/com/semicolon/domain/usecase/UseCase.kt
Labels: 프로젝트 설정

#8 🔀 :: (#7) users Retrofit Interface & data class
  data/src/main/java/com/semicolon/data/remote/api/UsersApi.kt
  data/src/main/java/com/semicolon/data/remote/request/users/InputHealthRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/users/UpdateProfileRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/users/UserChangePasswordRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/users/UserSignInRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/users/UserSignUpRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/users/VerifyPhoneNumberPasswordRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/users/VerifyPhoneNumberSignUpRequest.kt
  data/src/main/java/com/semicolon/data/remote/response/users/FindUserAccountResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/UserReissueResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/UserSignInResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/UserSignUpResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/inquirymypage/InquiryMypageResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/inquirymypage/TitleBadge.kt
  data/src/main/java/com/semicolon/data/remote/response/users/inquiryownbadges/Badge.kt
  data/src/main/java/com/semicolon/data/remote/response/users/inquiryownbadges/InquiryOwnBadgeResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/users/userinquiryprofile/TitleBadge.kt
  data/src/main/java/com/semicolon/data/remote/response/users/userinquiryprofile/UserInquiryProfileResponse.kt
Labels: 기능 추가

#12 🔀 :: (#12) notice Retrofit Interface & data class
  data/src/main/java/com/semicolon/data/remote/api/NoticesApi.kt
  data/src/main/java/com/semicolon/data/remote/response/notice/Notice.kt
  data/src/main/java/com/semicolon/data/remote/response/notice/NoticeDetailResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/notice/NoticeWriter.kt
Labels: 기능 추가

#10 🔀 :: (#6) ranks Retrofit Interface & data class
  data/src/main/java/com/semicolon/data/remote/api/RankApi.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/inquiryRank/school/SchoolRankResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/inquiryRank/user/UserRankResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/search/school/SearchSchoolResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/ranks/search/user/SearchUserResponse.kt
Labels: 기능 추가

#15 🔀 :: (#14) challenge api & response 구현
  data/src/main/java/com/semicolon/data/remote/api/ChallengeApi.kt
  data/src/main/java/com/semicolon/data/remote/response/challenge/ChallengeDetailResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/challenge/ChallengeListResponse.kt
  data/src/main/java/com/semicolon/data/remote/response/challenge/ChallengeParticipantListResponse.kt
Labels: 기능 추가

#21 🔀 :: (#5) exercise domain
  domain/src/main/java/com/semicolon/domain/entity/exercise/DailyExerciseEntity.kt
  domain/src/main/java/com/semicolon/domain/enum/GoalType.kt
  domain/src/main/java/com/semicolon/domain/param/.gitkeep
  domain/src/main/java/com/semicolon/domain/param/exercise/FinishMeasureExerciseParam.kt
  domain/src/main/java/com/semicolon/domain/param/exercise/StartMeasureExerciseParam.kt
  domain/src/main/java/com/semicolon/domain/repository/ExerciseRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchDailyExerciseRecordUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/FinishMeasureExerciseUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/IsMeasuringUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/StartMeasureExerciseUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/exercise/StartRecordExerciseUseCase.kt
Labels: 기능 추가

#19 🔀 :: (#18) Challenge Domain
  domain/src/main/java/com/semicolon/domain/entity/challenge/ChallengeDetailEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/challenge/ChallengeEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/challenge/ChallengeParticipantEntity.kt
  domain/src/main/java/com/semicolon/domain/enum/ChallengeScope.kt
  domain/src/main/java/com/semicolon/domain/repository/challenge/ChallengeRepository.kt
  domain/src/main/java/com/semicolon/domain/usecase/challenge/FetchChallengeDetailUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/challenge/FetchChallengeParticipantsUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/challenge/FetchChallengesUseCase.kt
  domain/src/main/java/com/semicolon/domain/usecase/challenge/PostParticipateChallengeUseCase.kt
Labels: 기능 추가

#22 🔀 :: (#11) images business logic
  data/src/main/java/com/semicolon/data/remote/api/ImagesApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/images/RemoteImagesDataSource.kt
  data/src/main/java/com/semicolon/data/remote/response/images/ImagesResponse.kt
  domain/src/main/java/com/semicolon/domain/usecase/image/.gitkeep
Labels: 기능 추가

#23 🔀 :: (#25) notices Entity 클래스 구현
  data/src/main/java/com/semicolon/data/remote/response/notice/NoticeListResponse.kt
  domain/src/main/java/com/semicolon/domain/entity/notice/NoticeDetailEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/notice/NoticeEntity.kt
  domain/src/main/java/com/semicolon/domain/entity/notice/NoticeWriterEntity.kt
  domain/src/main/java/com/semicolon/domain/repository/NoticeRepository.kt
Labels: 기능 추가

#28 🔀 :: (#27) exercise network logic
  data/src/main/java/com/semicolon/data/remote/api/ExerciseApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteExerciseDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteExerciseDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/request/exercise/FinishMeasureExerciseRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/exercise/SaveDailyExerciseRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/exercise/SendLocationRecordsRequest.kt
  data/src/main/java/com/semicolon/data/remote/request/exercise/StartMeasureExerciseRequest.kt
  data/src/main/java/com/semicolon/data/remote/response/exercise/ExerciseIdResponse.kt
  data/src/main/java/com/semicolon/data/util/HttpHandler.kt
  domain/src/main/java/com/semicolon/domain/exception/basic/BadRequestException.kt
  domain/src/main/java/com/semicolon/domain/exception/basic/ConflictException.kt
  domain/src/main/java/com/semicolon/domain/exception/basic/ForbiddenException.kt
  domain/src/main/java/com/semicolon/domain/exception/basic/NoInternetException.kt
  domain/src/main/java/com/semicolon/domain/exception/basic/NotFoundException.kt
  domain/src/main/java/com/semicolon/domain/exception/basic/ServerException.kt
  domain/src/main/java/com/semicolon/domain/exception/basic/TimeoutException.kt
  domain/src/main/java/com/semicolon/domain/exception/basic/UnauthorizedException.kt
  domain/src/main/java/com/semicolon/domain/exception/basic/UnknownException.kt
Labels: 기능 추가

#34 🔀 :: (#33) images datasource
  data/src/main/java/com/semicolon/data/remote/api/ImagesApi.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteImagesDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteImagesDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/image/ImagesResponse.kt
Labels: 기능 추가

#40 🔀 :: (#39) database error fix
  data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
Labels: 버그

#44 🔀 :: (#31) Rank부분 datasource & datasourceImpl
  data/src/main/java/com/semicolon/data/remote/api/.gitkeep
  data/src/main/java/com/semicolon/data/remote/datasource/.gitkeep
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSource.kt
  data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/remote/response/.gitkeep
  data/src/main/java/com/semicolon/data/repository/.gitkeep
  domain/src/main/java/com/semicolon/domain/entity/.gitkeep
  domain/src/main/java/com/semicolon/domain/usecase/rank/.gitkeep
Labels: 기능 추가

#42 🔀 :: (#41) school api, entity 작성
  data/src/main/java/com/semicolon/data/remote/api/SchoolApi.kt
  data/src/main/java/com/semicolon/data/remote/response/school/SearchSchoolResponse.kt
Labels: 기능 추가

#38 🔀 :: (#30) exercise business logic (local)
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  data/build.gradle.kts
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSource.kt
  data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSourceImpl.kt
  data/src/main/java/com/semicolon/data/local/entity/exercise/LocationRecordEntity.kt
  data/src/main/java/com/semicolon/data/local/entity/exercise/WalkRecordEntity.kt
  data/src/main/java/com/semicolon/data/local/param/PeriodParam.kt
  data/src/main/java/com/semicolon/data/local/storage/FitnessDataStorage.kt
  data/src/main/java/com/semicolon/data/local/storage/FitnessDataStorageImpl.kt
Labels: 기능 추가
